services:
  angular:
    container_name: angular-app
    build:
      context: ./frontend/blog
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - node-server


  node-server:
    container_name: node-api    
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      - MONGODB_URI=mongodb+srv://twwai:KTp5wYwutrLHPLT@cluster0.ooees.mongodb.net/IoT?retryWrites=true&w=majority 
 